### ISSUE TITLE
Setting the version number for .NET Core projects

### ISSUE THREAD

**Issue by rw-nowakpiotr** [cake-contrib/Cake.Bumpy#7]
Setting the version number for .NET Core projects - CSPROJ - not JSON projects, e.g.

```
<PropertyGroup>
   <VersionPrefix>1.0.0</VersionPrefix>
   <VersionSuffix>alpha</VersionSuffix>
</PropertyGroup>
```

**Comment by fwinkelbauer** [comment]
Hi,

currently this is not possible because [Bumpy](https://github.com/fwinkelbauer/Bumpy) (the command line tool behind `Cake.Bumpy`) does not support these types of split versions. I need some time to think about this to find out how I could handle such cases in a sane way. (Currently each line is processed on it's own)

May I suggest a workaround? According to this [link](https://docs.microsoft.com/en-us/dotnet/core/tools/project-json-to-csproj#version) it seems to be possible to create a combinated version tag such as:

```
<PropertyGroup>
  <Version>2.0.0-alpha</Version>
</PropertyGroup>
```

Using a `bumpyconfig` like this:

```
MyProject.csproj = <Version>(?<version>\d+\.\d+\.\d+-.*)</Version>
```

You could do something like:

```
// 2.0.0-alpha -> 3.0.0-alpha
bumpy increment 1
// 3.0.0-alpha -> 3.0.0
bumpy write 3.0.0
```

Could this work for you?

**Edit:** If this was a solution I could add a new command/alias to change the label of a version. I am thinking about something like this:

```
// 2.0.0-alpha -> 2.0.0-beta
bumpy label -beta
// 2.0.0-beta -> 2.0.0
bumpy label ""

**Comment by rw-nowakpiotr** [comment]
I appreciate your answer. Thank you very much. I will definitely use this workaround, but in a long term we have to come up with something better.

**Comment by fwinkelbauer** [comment]
I have implemented the proposed command "bumpy label" [here](https://github.com/cake-contrib/Cake.Bumpy/issues/8). A release (including an update to Cake.Bumpy) will follow soon.

Further work regarding your main issue can be tracked [here](https://github.com/fwinkelbauer/Bumpy/issues/30). I can't give you a timeline, but I might figure something out in the future.

Thanks
